name: NashboroughPlugin
main: to.us.nashboroughmc.nashboroughplugin.NashboroughPlugin
version: SNAPSHOT-01

commands:
  apply:
    description: sends in an application to become an official Nashbro
    usage: /apply
  
  reviewapps:
    description: review pending applications and approve or deny them
    usage: /reviewapps
    permission: op
    
  reviewapp:
    description: review application of the player given
    usage: /reviewapp <username> [verdict]
    permission: op