name: NashboroughPlugin
main: to.us.nashboroughmc.nashboroughplugin.NashboroughPlugin
version: SNAPSHOT-01

commands:
  apply:
    description: sends in an application to become an official Nashbro
    usage: /apply
  
  reviewapps:
    desciption: review pending applications and approve or deny them
    usage: /reviewapps